### PR TITLE
Add link to WWDC session summaries

### PR DESCRIPTION
**Pull request by Blackjacx**
Usually it is much faster to read through some bullet points instead of watching a 50 min session video. This github repo aims to offer right this!

### CODE REVIEW

**Comment by nataliapanferova** [comment]
👍

**Comment by stherold** [comment]
Thanks a lot :-)

**Comment by nataliapanferova** [comment]
It looks really useful, thank you!

**Comment by stherold** [comment]
Can we put it maybe in a more prominent location on the page? Last year it got 2.3K stars on github so I think it can help a lot of people and it would be sad if they won't find it.

**Comment by nataliapanferova** [comment]
@twostraws what would be a good section for this one?

**Comment by twostraws** [comment]
Hmm. How about "Summaries" or similar? We could put that above Swift in the list, and it leaves scope for folks who write other "things I found during the week" posts to contribute.

**Comment by nataliapanferova** [comment]
Sounds good, I'll add "Summaries" section then.

**Pull request merged**
