### PR TITLE
Added Code Completion to list of podcasts

### PR DESCRIPTION
**Pull request by dimitribouniol**
## Checklist
* [x] The link is freely available for everyone to read.
* [x] The link hasn't already been submitted.
* [x] I placed the link at the bottom of its category.
* [x] The link is in the correct format: `[Post name](link to post) from [Author name](optional author link)`. For example, `[My WWDC 2020 Wishlist](https://beckyhansmeyer.com/2020/05/13/my-wwdc-2020-wishlist/) from Becky Hansmeyer`.
* [x] The link isn't about rumors.
* [x] The linked material is suitable for a general audience.

## Optional for links to paid products
* [ ] The link regards a discounted paid product. I put it in the Offers category.
* [ ] This is the only Offers link I have submitted or updated. (Send just one link for multiple offers to avoid overwhelming the list.)

### CODE REVIEW

**Comment by twostraws** [comment]
Are you specifically streaming live during WWDC? If so, this is a great place to list the podcast. On the flip side, if you've recorded an episode *after* WWDC that's about WWDC, please submit a link to the episode here.

**Comment by dimitribouniol** [comment]
We'll be streaming live on Monday — I'll update the link to a placeholder stream in just a moment if that works better!

**Comment by twostraws** [comment]
Maybe add "Live" or similar as well?

**Comment by dimitribouniol** [comment]
Just updated — does that look better?

**Comment by twostraws** [comment]
Thank you!

**Comment by dimitribouniol** [comment]
Thanks as well! Really appreciate it 😊

**Pull request merged**
