### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mikaelacaron**
Add link to CodeWithChris sale of CodeWithChris+. This is using my affiliate link, that Chris has allowed me to use. Which also helps him determine how many sales may come from this post. I can switch the link if that is not allowed.

## Checklist
* [x] The link is freely available for everyone to read.
* [x] The link hasn't already been submitted.
* [x] I placed the link at the bottom of its category.
* [x] The link is in the correct format: `[Post name](link to post) from [Author name](optional author link)`. For example, `[My WWDC 2020 Wishlist](https://beckyhansmeyer.com/2020/05/13/my-wwdc-2020-wishlist/) from Becky Hansmeyer`.
* [x] The link isn't about rumors.
* [x] The linked material is suitable for a general audience.

## Optional for links to paid products
* [x] The link regards a discounted paid product. I put it in the Offers category.
* [x] This is the only Offers link I have submitted or updated. (Send just one link for multiple offers to avoid overwhelming the list.)

### CODE REVIEW

**Comment by twostraws** [comment]
I don't have any particularly strong views on using affiliate links here – @SAllen0400 / @subdigital, what do you think?

**Comment by SAllen0400** [comment]
I don't think it's an issue as long as the owner of the content can take over the link. For example, if Chris wanted to post the link himself, that would replace any affiliate links.

**Comment by subdigital** [comment]
I’m inclined to have neutral (non-affiliate) links personally.

**Comment by twostraws** [comment]
Yeah, I know what you mean, Ben. I like Sean's solution: use this for now, but I'll message Chris and let him know he's welcome to remove the affiliate link at any point in the future. Thanks, folks!

**Pull request merged**
