### PR TITLE
Create SwiftUI Projects

### PR DESCRIPTION
**Pull request by mhuq1138**
## Checklist
* [ ] The link is freely available for everyone to read.
* [ ] The link hasn't already been submitted.
* [ ] I placed the link at the bottom of its category.
* [ ] The link is in the correct format: `[Post name](link to post) from [Author name](optional author link)`. For example, `[My WWDC 2020 Wishlist](https://beckyhansmeyer.com/2020/05/13/my-wwdc-2020-wishlist/) from Becky Hansmeyer`.
* [ ] The link isn't about rumors.
* [ ] The linked material is suitable for a general audience.

## Optional for links to paid products
* [ ] The link regards a discounted paid product. I put it in the Offers category.
* [ ] This is the only Offers link I have submitted or updated. (Send just one link for multiple offers to avoid overwhelming the list.)

### CODE REVIEW

**Comment by twostraws** [comment]
Thank you for your pull request! Could you perhaps clarify this a little more? It just seems to be a link to your GitHub homepage.

**Comment by mhuq1138** [comment]
I wanted my GitHub homepage containing many SwftUI and other projects and associated documents to get more public exposure. If you can think a way to include on the SwiftUI section, it would be very much appreciated.

Thank you.

Mazharul Huq

**Comment by twostraws** [comment]
This repository is specifically for articles, videos, and podcasts about APIs that were introduced at WWDC20; I don't think your link is a great fit – perhaps there's a different repository that might work better?

**Comment by mhuq1138** [comment]
Thank you. Perhaps you might have some recommendation.

Mazharul Huq

**Comment by mhuq1138** [comment]
I have a repository on GitHub with iOS 14 Date Picker New features (https://github.com/mhuq1138/ios-14-date-picker-new-features <https://github.com/mhuq1138/ios-14-date-picker-new-features>). I am having some difficulty creating a pull request. I would appreciate if you can add this link to SwiftUI section two/straws/wwdc.

Thank you.

Mazharul Huq

**Pull request closed without merging**
