### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SwiftSIQI**
## Checklist
* [X] The link is freely available for everyone to read.
* [X] The link hasn't already been submitted.
* [X] I placed the link at the bottom of its category.
* [X] The link is in the correct format: `[Post name](link to post) from [Author name](optional author link)`. For example, `[My WWDC 2020 Wishlist](https://beckyhansmeyer.com/2020/05/13/my-wwdc-2020-wishlist/) from Becky Hansmeyer`.
* [X] The link isn't about rumors.
* [X] The linked material is suitable for a general audience.

## Optional for links to paid products
* [ ] The link regards a discounted paid product. I put it in the Offers category.
* [ ] This is the only Offers link I have submitted or updated. (Send just one link for multiple offers to avoid overwhelming the list.)

### CODE REVIEW

**Comment by SketchK** [comment]
Hi, @twostraws , I'd like to help merge pull requests! Could you add me to the list?
By the way, I think the links to [Daniel Steinberg](https://twitter.com/dimsumthinking) and [Kaya Thomas](https://twitter.com/kthomas901) need updating
And We also add a watch party in HANGZHOU 🎉
🇨🇳 June 10th, 11pm CST: [WWDC24.playground Watch Party](https://wwdc24.swiftgg.team/en/), HANGZHOU, China

**Comment by twostraws** [comment]
I'm happy to merge this in and add you, but could you please check that Twitter link? It doesn't seem quite right.

**Comment by SwiftSIQI** [comment]
@twostraws Hi, Paul, I fix that error!
Thank you!

**Comment by twostraws** [comment]
Thank you! One last thing before I merge this: is your name normally written in English using all uppercase letters?

**Comment by SwiftSIQI** [comment]
> Thank you! One last thing before I merge this: is your name normally written in English using all uppercase letters?

Haha! Good Question! 
This is just my personal preference, but I think your suggestion is great. I will change it to a more common way!

**Comment by twostraws** [comment]
Thank you! 🙌

**Pull request merged**
